import { jsx as _jsx, jsxs as _jsxs, Fragment as _Fragment } from "react/jsx-runtime";
//@ts-nocheck
import { Head, Link } from '@inertiajs/react';
import Layout from "@/Layouts/Layout";
import { CircleArrowOutUpRight, Receipt } from "lucide-react";
import { cn } from "@/lib/utils";
import { Button } from "@/primitives/ui/button";
import { Card, CardContent, CardDescription, CardFooter, CardHeader, CardTitle, } from "@/primitives/ui/card";
export function InfoCard({ className, details, ...props }) {
    return (_jsxs(Card, { className: cn("w-[380px]", className), children: [_jsxs(CardHeader, { children: [_jsx(CardTitle, { children: "Thank you for choosing Us." }), _jsx(CardDescription, { children: "We will process your order with these information." })] }), _jsxs(CardContent, { className: "grid gap-4", children: [_jsxs("div", { className: " flex items-center space-x-4 rounded-md border p-4", children: [_jsx(Receipt, {}), _jsxs("div", { className: "flex-1 space-y-1", children: [_jsx("p", { className: "text-sm font-medium leading-none", children: "A Receipt was sent." }), _jsx("p", { className: "text-sm text-muted-foreground", children: "Separate order confirmation will be sent shortly." })] })] }), _jsxs("div", { children: [_jsxs("div", { className: "mb-4 grid grid-cols-[25px_1fr] items-start pb-4 last:mb-0 last:pb-0", children: [_jsx("span", { className: "flex h-2 w-2 translate-y-1 rounded-full bg-sky-500" }), _jsxs("div", { className: "space-y-1", children: [_jsx("p", { className: "text-sm font-medium leading-none", children: "We will deliver to" }), _jsxs("p", { className: "text-sm text-muted-foreground", children: [details.address.line1, ",", details.address.city, " ", details.address.postal_code] })] })] }), _jsxs("div", { className: "mb-4 grid grid-cols-[25px_1fr] items-start pb-4 last:mb-0 last:pb-0", children: [_jsx("span", { className: "flex h-2 w-2 translate-y-1 rounded-full bg-sky-500" }), _jsxs("div", { className: "space-y-1", children: [_jsx("p", { className: "text-sm font-medium leading-none", children: "We will call you on" }), _jsx("p", { className: "text-sm text-muted-foreground", children: details.phone })] })] }), _jsxs("div", { className: "mb-4 grid grid-cols-[25px_1fr] items-start pb-4 last:mb-0 last:pb-0", children: [_jsx("span", { className: "flex h-2 w-2 translate-y-1 rounded-full bg-sky-500" }), _jsxs("div", { className: "space-y-1", children: [_jsx("p", { className: "text-sm font-medium leading-none", children: "It would take us" }), _jsx("p", { className: "text-sm text-muted-foreground", children: "8 minutes to fulfill your order" })] })] })] })] }), _jsx(CardFooter, { children: _jsx(Button, { className: "w-full", asChild: true, children: _jsxs(Link, { href: "/", children: [_jsx(CircleArrowOutUpRight, { className: "mr-2 h-4 w-4" }), " Go checkout more"] }) }) })] }));
}
export default function PostcheckoutSuccess({ cuisines, categories, details }) {
    return (_jsxs(_Fragment, { children: [_jsx(Head, { title: "Post Checkout | Failed Transaction" }), _jsx(Layout, { cuisines: cuisines, categories: categories, children: _jsx("section", { className: "flex justify-around items-start my-12", children: _jsx(InfoCard, { details: details }) }) })] }));
}
